### ISSUE TITLE
New ArgonNX-SE with autoboot support !

### ISSUE THREAD

**Issue by buggii** [Switch-Hax-uf2/switch-.uf2-files#2]
Hi ! Here it is the new ArgonNX-SE payload with autoboot support, can you please convert it to .uf2  !

https://mega.nz/file/Op1WyYYJ#OV0nF31hSrm575zBE_6kgxgGf7HU9AMaZYtz3_L5lMw

Thank you very much !

**Comment by Switch-Hax-uf2** [comment]
Okay, I have added the new file.
